#define PROMT std::cout << "XMLP> ";
#define NO_FILE "XMLP> XML file is not loaded. Try load a valid XMl language file first"
#define TRY_FILE "XMLP> Trying to open file: "
#define TRY_REM_ID "XMLP> Trying to remove ID: "
#define ID_NOT_INT "XMLP> the input parameter is not an integer. Not ID should be and Integer."
#define FILE_LOADED "XMLP> XML file loaded"
#define FILE_LOAD_ERROR "XMLP> XML failed to load. Reason: "
#define REM_ID_WRONG_ID "XMLP> Notification ID not valid. Has to be an integer number greater than 0. Command '-r ' is ignored"
#define FILE_NOT_EXIST "XMLP> File does not exist. Try loading an XML language file using command: -o <path\filename"
#define TEXT_MISSING "Missing Notification/Menu_item text. Add text using command: -a <Textstring>"